# Generated by Django 5.2.1 on 2025-06-04 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataintegration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accessright',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='accessright',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='accessright',
            unique_together={('user', 'resource', 'version')},
        ),
    ]
