# Generated by Django 5.2.1 on 2025-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0002_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('can_view_products', models.BooleanField(default=False)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_update_product', models.BooleanField(default=False)),
                ('can_view_most_expensive', models.BooleanField(default=False)),
            ],
        ),
    ]
