# Generated by Django 5.2.1 on 2025-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0003_userright'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userright',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
