# Generated by Django 5.2.1 on 2025-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0004_alter_userright_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userright',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
